# Logfile Processing

In [1]:
import warnings
import pandas as pd
warnings.filterwarnings('ignore')

In [2]:
file_name = "50EA1DAA6NA002459-1 (1).csv"

In [11]:
df = pd.read_csv(file_name)

df['new_timestamp'] = df['@timestamp'].apply(lambda x: x.replace("@","").replace("+\s","").strip())
df['new_timestamp'] = pd.to_datetime(df['new_timestamp'])

# df.sort_values(by='new_timestamp', inplace=True, ignore_index=True)

print(df.shape)
df.head()

(101448, 16)

,@log_name,@log_name.keyword,@timestamp,_id,_index,_score,_type,host,host.keyword,ident,ident.keyword,message,message.keyword,pid,pid.keyword,new_timestamp
0,module.kern.info,module.kern.info,"Jan 25, 2022 @ 20:49:18.000",l1u3lH4BsVcCeYgrgUty,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,kernel,kernel,[64503.520232] IPv6: ADDRCONF(NETDEV_UP): br0....,[64503.520232] IPv6: ADDRCONF(NETDEV_UP): br0....,-,-,2022-01-25 20:49:18
1,module.kern.info,module.kern.info,"Jan 25, 2022 @ 20:49:18.000",mFu3lH4BsVcCeYgrgUty,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,kernel,kernel,[64503.743974] IPv6: ADDRCONF(NETDEV_UP): br0....,[64503.743974] IPv6: ADDRCONF(NETDEV_UP): br0....,-,-,2022-01-25 20:49:18
2,module.kern.info,module.kern.info,"Jan 25, 2022 @ 20:49:18.000",mVu3lH4BsVcCeYgrgUty,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,kernel,kernel,[64503.967280] IPv6: ADDRCONF(NETDEV_UP): br0....,[64503.967280] IPv6: ADDRCONF(NETDEV_UP): br0....,-,-,2022-01-25 20:49:18
3,module.user.notice,module.user.notice,"Jan 25, 2022 @ 20:49:18.000",FVu3lH4BsVcCeYgriUw0,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,ARP_MON,ARP_MON,"br0.3 missing IP, reiniting...","br0.3 missing IP, reiniting...",-,-,2022-01-25 20:49:18
4,module.user.notice,module.user.notice,"Jan 25, 2022 @ 20:49:18.000",Flu3lH4BsVcCeYgriUw0,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,ARP_MON,ARP_MON,"br0.5 missing IP, reiniting...","br0.5 missing IP, reiniting...",-,-,2022-01-25 20:49:18

In [12]:
start_at = "token received is 1"
end_at = "Waiting for the Download notification ... "
routing_activation_string = "In the routing activation"
ip_connection_string = "Successfully connected to"
request_string = "request_bytes"
response_string = "response:"

In [13]:
for col in df.columns:
    n_records = len(df.loc[df[col]==start_at])
    if n_records >= 1:
        print(col, n_records)
        
for col in df.columns:
    n_records = len(df.loc[df[col]==end_at])
    if n_records >= 1:
        print(col, n_records)
        
for col in df.columns:
    n_records = len(df.loc[df[col]==ip_connection_string])
    if n_records >= 1:
        print(col, n_records)

message 1
message.keyword 1
message 1
message.keyword 1

In [14]:
start_index = df[df['message']==start_at].index.tolist()
end_index = df[df['message']==end_at].index.tolist()
print(list(zip(start_index, end_index)))

[(99572, 3796)]

In [15]:
df_sub = df.loc[start_index[0]:,]
print(df_sub.shape)
df_sub.head()

(1876, 16)

,@log_name,@log_name.keyword,@timestamp,_id,_index,_score,_type,host,host.keyword,ident,ident.keyword,message,message.keyword,pid,pid.keyword,new_timestamp
99572,module.daemon.info,module.daemon.info,"Jan 25, 2022 @ 18:20:27.000",zrUvlH4BsVcCeYgrZRkL,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,FLASH_SERVICE,FLASH_SERVICE,token received is 1,token received is 1,-,-,2022-01-25 18:20:27
99573,module.daemon.info,module.daemon.info,"Jan 25, 2022 @ 18:20:27.000",z7UvlH4BsVcCeYgrZRkL,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,FLASH_SERVICE,FLASH_SERVICE,Status of flash progress thread set to 0.,Status of flash progress thread set to 0.,-,-,2022-01-25 18:20:27
99574,module.daemon.info,module.daemon.info,"Jan 25, 2022 @ 18:20:27.000",0LUvlH4BsVcCeYgrZRkL,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,FLASH_SERVICE,FLASH_SERVICE,Received download notification,Received download notification,-,-,2022-01-25 18:20:27
99575,module.daemon.info,module.daemon.info,"Jan 25, 2022 @ 18:20:27.000",0bUvlH4BsVcCeYgrZRkL,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,FLASH_SERVICE,FLASH_SERVICE,Config Path: /var/sota/storage/secondary_ecus/...,Config Path: /var/sota/storage/secondary_ecus/...,-,-,2022-01-25 18:20:27
99576,module.daemon.info,module.daemon.info,"Jan 25, 2022 @ 18:20:27.000",0rUvlH4BsVcCeYgrZRkL,logstash-2022.01.26,-,_doc,50EA1DAA6NA002459,50EA1DAA6NA002459,FLASH_SERVICE,FLASH_SERVICE,[manifest_info]Correct DoIP server count,[manifest_info]Correct DoIP server count,-,-,2022-01-25 18:20:27

In [16]:
ip_df = df_sub.loc[df.message.str.contains(ip_connection_string),['message','new_timestamp']]
ip_df.reset_index(drop=True, inplace=True)
ip_df.rename(columns={'message':'connect_msg','new_timestamp':'connect_ts'},inplace=True)
print(ip_df.shape)
ip_df.head()

(10, 2)

                              connect_msg          connect_ts
0  Successfully connected to  192.168.1.1 2022-01-25 18:20:27
1  Successfully connected to  192.168.1.2 2022-01-25 18:20:27
2  Successfully connected to  192.168.1.3 2022-01-25 18:20:27
3  Successfully connected to  192.168.1.4 2022-01-25 18:20:27
4  Successfully connected to  192.168.1.5 2022-01-25 18:20:27

In [29]:
# route_df = df_sub.loc[df.message.str.contains(routing_activation_string),['message','new_timestamp']]
# route_df.reset_index(drop=True, inplace=True)
# route_df.rename(columns={'message':'route_msg','new_timestamp':'route_ts'},inplace=True)
# print(route_df.shape)
# route_df

In [17]:
req_df = df_sub.loc[df.message.str.contains(request_string),['message','new_timestamp']]
req_df.reset_index(drop=True, inplace=True)
req_df.rename(columns={'message':'request_msg','new_timestamp':'request_ts'},inplace=True)
print(req_df.shape)
req_df.head()

(10, 2)

            request_msg          request_ts
0  [0] request_bytes 19 2022-01-25 18:20:27
1  [1] request_bytes 19 2022-01-25 18:20:27
2  [2] request_bytes 19 2022-01-25 18:20:27
3  [3] request_bytes 19 2022-01-25 18:20:27
4  [4] request_bytes 19 2022-01-25 18:20:27

In [18]:
resp_df = df_sub.loc[df.message.str.contains(response_string),['message','new_timestamp']]
resp_df.reset_index(drop=True, inplace=True)
resp_df.rename(columns={'message':'response_msg','new_timestamp':'response_ts'},inplace=True)
print(resp_df.shape)
resp_df.head()

(10, 2)

                   response_msg         response_ts
0  [0] response: read_bytes: 17 2022-01-25 18:20:27
1  [1] response: read_bytes: 17 2022-01-25 18:20:27
2  [2] response: read_bytes: 17 2022-01-25 18:20:27
3  [3] response: read_bytes: 17 2022-01-25 18:20:27
4  [4] response: read_bytes: 17 2022-01-25 18:20:27

In [20]:
# alfa = pd.concat([ip_df, req_df, resp_df], axis=1)
# alfa = alfa[['connect_msg','request_msg','response_msg','connect_ts','request_ts','response_ts']]
# alfa['req_resp_secs'] = (alfa['request_ts'] - alfa['response_ts']).astype('timedelta64[s]')
print(alfa.shape)
# alfa.head()
alfa

(10, 7)

,connect_msg,request_msg,response_msg,connect_ts,request_ts,response_ts,req_resp_secs
0,Successfully connected to 192.168.1.1,[0] request_bytes 19,[0] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
1,Successfully connected to 192.168.1.2,[1] request_bytes 19,[1] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
2,Successfully connected to 192.168.1.3,[2] request_bytes 19,[2] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
3,Successfully connected to 192.168.1.4,[3] request_bytes 19,[3] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
4,Successfully connected to 192.168.1.5,[4] request_bytes 19,[4] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
5,Successfully connected to 192.168.1.6,[5] request_bytes 19,[5] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
6,Successfully connected to 192.168.1.7,[6] request_bytes 19,[6] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
7,Successfully connected to 192.168.1.9,[7] request_bytes 19,[7] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
8,Successfully connected to 192.168.1.71,[8] request_bytes 19,[8] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0
9,Successfully connected to 192.168.1.12,[9] request_bytes 19,[9] response: read_bytes: 17,2022-01-25 18:20:27,2022-01-25 18:20:27,2022-01-25 18:20:27,0.0

In [22]:
alfa.connect_msg.apply(lambda x: x.replace("Successfully connected to ","").strip())

0     192.168.1.1
1     192.168.1.2
2     192.168.1.3
3     192.168.1.4
4     192.168.1.5
5     192.168.1.6
6     192.168.1.7
7     192.168.1.9
8    192.168.1.71
9    192.168.1.12
Name: connect_msg, dtype: object

In [ ]:
alfa.to_csv("response_alfa.csv",index=False)

In [34]:
beta = alfa[alfa.req_resp_secs > 10]
beta

Empty DataFrame
Columns: [connect_msg, request_msg, response_msg, connect_ts, request_ts, response_ts, req_resp_secs]
Index: []

In [22]:
beta.to_csv("response.txt",index=False)